services:
  web:
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - static_volume:/app/staticfiles_collected
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    restart: always
