# Generated by Django 5.2.1 on 2025-05-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of the team.', max_length=100, unique=True, verbose_name='Team Name')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(help_text='Used to determine age category if applicable.', verbose_name='Date of Birth')),
                ('start_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Start Number')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racers', to='race_core.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Racer',
                'verbose_name_plural': 'Racers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
