# Generated by Django 5.2.1 on 2025-06-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_core', '0003_alter_racerun_recorded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soapbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The  name of the soapbox.', max_length=100, unique=True, verbose_name='Soapbox Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Soapbox',
                'verbose_name_plural': 'Soapboxes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='racer',
            name='soapbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racers', to='race_core.soapbox', verbose_name='Soapbox'),
        ),
    ]
