# Generated by Django 5.2.1 on 2025-06-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_core', '0004_soapbox_racer_soapbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapbox',
            name='name',
            field=models.CharField(help_text='The name of the soapbox.', max_length=100, unique=True, verbose_name='Soapbox Name'),
        ),
    ]
