# Generated by Django 5.2.3 on 2025-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_core', '0005_alter_soapbox_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='soapbox_class',
            field=models.CharField(choices=[('LRJ', 'Luftreifen Junior'), ('LRS', 'Luftreifen Senior'), ('HRJ', 'Hartreifen Junior'), ('HRS', 'Hartreifen Senior'), ('XKL', 'X-Klasse'), ('VTR', 'Veteranen'), ('UNK', 'Unknown')], default='UNK', help_text='The class the racer is competing in.', max_length=3, verbose_name='Soapbox Class'),
        ),
    ]
